spring:
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        default_schema: DATABROKER
        naming:
          physical-strategy: com.bayer.accrual.databroker.configurations.CustomNamingStrategy
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.json
    default-schema: DATABROKER
---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
#                type: trace
